[package]
name = "caffeine_"
version = "0.1.1"
edition = "2021"
description = "Simple hash table implementation using open addressing. Written for use with my crafting interpeters tutorial implementation."
license = "MIT"

[dependencies]
rand = "0.8.5"
